version: '3.8'

services:
 nginx:
    build: ./docker/nginx 
    ports: 
     - "8080:80" 
    depends on: 
     - node-service 

node-service:
 build: ./docker/api 
 environment:
  - DB_HOST=db 
  - DB_USERNAME=app_user 
  - DB_PASSWORD= P@ssw0rd0 
  - DB_DATABASE=app_db 
  - depends_on: db
  
db:
  build: ./docker/db 
  environment: 
    - MYSQL_ROOT_PASSWORD=P@ssw0rd 
    - MYSQL_DATARASE=app_db
    - MYSQL_USER=app_user 
    - MYSQL_PASSWORD=P@ssw0rd0
  volumes:
    - db_data:/var/lib/mysql 
    
volumes:
 db_data: